### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Iscle** [t3chkid/Musify#6]
Hi!

Love the project, what's the license for it?

Regards,
Iscle

**Comment by t3chkid** [comment]
Thank you! Glad you liked it! Currently, it doesn't have any license. This implies that all rights are reserved and the project is not open source.

**Comment by Iscle** [comment]
Okay, no problem! Keep up the good work :)

Regards,
Iscle

**Comment by drsounds** [comment]
Hi,

Would be fun if you could add a OS license so I can fork it and customize it for my needs

**Comment by t3chkid** [comment]
> Hi,
> 
> Would be fun if you could add a OS license so I can fork it and customize it for my needs

- Hey there. The thing is, since this is clearly a clone of a very popular app, it's kinda difficult to select a license.

**Comment by drsounds** [comment]
Hi,

I just guessed that but thanks for clearing this out.

Den tors 6 apr. 2023 13:05Technophile ***@***.***> skrev:
